const books = [
    {
      id: 1,
      title: "The Alchemist",
      author: "Paulo Coelho",
      genre: "Fiction",
      price: 299,
      image: "alchemist.jpg", 

    },
    {
      id: 2,
      title: "Clean Code",
      author: "Robert C. Martin",
      genre: "Programming",
      price: 450,
      image: "clean code.jpg",
      
    },
    {
      id: 3,
      title: "kolaiudhir kaalam",
      author: "Sujatha",
      genre: "Fiction",
      price: 199,
      image: "koliudhir kalam.webp",
   
    },
    {
      id: 4,
      title: "Before the coffee gets cold series",
      author: "Toshikazu Kawaguchi",
      genre: "Fiction",
      price: 599,
      image: "coffee.jpg",
    },
    {
      id: 5,
      title: "Jayakandhan kadhaigal",
      author: "Jayakandhan",
      genre: "Short stories",
      price: 299,
      image: "jayakandhan 2.jpg",
    },
    {
      id: 6,
      title: "Attitude is Everything",
      author: "Jeff Keller",
      genre: "Self-help",
      price: 99,
      image: "attitude is everything.jpg",
    },
    {
      id: 7,
      title: "Atomic Habits",
      author: "Paulo Coelho",
      genre: "Self-help",
      price: 299,
      image: "atomic habis.jpg",

    },
    {
      id: 8,
      title: "Without Merit",
      author: "Robert C. Martin",
      genre: "Fantasy/Fiction",
      price: 459,
      image: "without merit.jpg",
      
    },
    {
      id: 9,
      title: "Silent Patient",
      author: "Alex Michaelides",
      genre: "Fiction",
      price: 199,
      image: "silent patient.jpg",
   
    },
    {
      id: 10,
      title: "Ponniyin Selavan part-1",
      author: "Kalki",
      genre: "Fiction",
      price: 399,
      image: "ps.jpg",
    },
    {
      id: 11,
      title: "Mindset",
      author: "Dr. Carol S. Dweck",
      genre: "Self-help",
      price: 99,
      image: "mindset.jpg",
    },
    {
      id: 12,
      title: "Sila Nerangalil Sila manithargal",
      author: "Jayakandhan",
      genre: "Fiction",
      price: 199,
      image: "snsm.jpg",
   
    },
    {
      id: 13,
      title: "Malai Maaligai",
      author: "Sujatha",
      genre: "Fantasy/Fiction",
      price: 299,
      image: "malai maaligai.jpg",
    },
    {
      id: 14,
      title: "Jayakanthan Kadhaigal",
      author: "Jayakandhan",
      genre: "Fiction",
      price: 199,
      image: "jayakandhan.jpg",
    },
    {
      id: 15,
      title: "Varity",
      author: "Colleen Hoover",
      genre: "Thriller/Fiction",
      price: 199,
      image: "varity.jpg",
    },
    {
      id: 16,
      title: "How to Win and Influence People",
      author: "Dale Carnegie",
      genre: "Self-help",
      price: 299,
      image: "influence.png",
    },
    {
      id: 17,
      title: "Secret",
      author: "JRhonda Byrne",
      genre: "Self-help",
      price: 399,
      image: "secret.jpg",
    },
    {
      id: 18,
      title: "The art of being alone",
      author: "Renuka Gavrani",
      genre: "Self-help",
      price: 299,
      image: "art.jpg",
    }
  ];
  